#!/usr/bin/env python3
"""
Characterize 3 parameter sets against all 27 experimental conditions.

Phase 1: Run N jitter trials per condition, select best-fit trial (closest to target).
Phase 2: Re-run best-fit trials with video recording.

Usage:
    uv run python characterize_params.py
    uv run python characterize_params.py --n-trials 10 --no-video
"""

import argparse
import csv
import multiprocessing
import pathlib
import sys
import time
from typing import Any

import numpy as np

from config_new import (
    MJCF_PATHS,
    REFERENCE_DATA as FLAT_REFS,
    SETTLE_TIME,
    SIM_DURATION as FLAT_SIM_DURATION,
    sim_params_from_point,
    space,
)
from config_step import (
    REFERENCE_DATA as STEP_REFS,
    SIM_DURATION as STEP_SIM_DURATION,
    STEP_PRESET,
    STEP_START_X,
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PARAM_NAMES = [dim.name for dim in space]

# Step terrain XML paths (pre-generated by optimizer_step.py)
n_steps = STEP_PRESET["step_count"]
h_mm = STEP_PRESET["step_height"] * 1000
l_mm = STEP_PRESET["step_length"] * 1000
lead_mm = STEP_PRESET["flat_lead"] * 1000
STEP_TAG = f"step_{n_steps}x{h_mm:.0f}mm_{l_mm:.1f}L_{lead_mm:.0f}lead"

STEP_MJCF_PATHS = {}
for scene, base_xml in MJCF_PATHS.items():
    src_dir = pathlib.Path(base_xml).parent
    stem = pathlib.Path(base_xml).stem
    step_xml = str(src_dir / f"{stem}_{STEP_TAG}.xml")
    STEP_MJCF_PATHS[scene] = step_xml

# 3 parameter sets to evaluate
PARAM_SETS = {
    "flat_all": "results/20260225T003517_flat_16dim_corrected_warm",
    "flat_10_30_50": "results/20260225T122342_flat_10_30_50",
    "step_16dim": "results/20260224T175707_step_16dim_v1",
}

MORPH_MAP = {"scene1": "2-leg", "scene2": "4-leg", "scene4": "leg", "scene_wheel": "wheel"}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_best_params(run_dir: str) -> dict[str, float]:
    """Load best (last row) params from optimization_bests.csv."""
    csv_path = pathlib.Path(run_dir) / "optimization_bests.csv"
    with open(csv_path) as f:
        rows = list(csv.DictReader(f))
    best = rows[-1]
    return {name: float(best[name]) for name in PARAM_NAMES}


def params_dict_to_point(params: dict[str, float]) -> list[float]:
    """Convert named params dict to ordered point vector for sim_params_from_point()."""
    return [params[name] for name in PARAM_NAMES]


def _extract_flat_velocity(trajectory: list[dict]) -> float:
    """Extract average forward velocity using settle time gate."""
    start_state = trajectory[0]
    for state in trajectory:
        if state["time"] >= SETTLE_TIME:
            start_state = state
            break
    final_state = trajectory[-1]
    dt = final_state["time"] - start_state["time"]
    if dt < 1e-6:
        return 0.0
    return (final_state["pos"][0] - start_state["pos"][0]) / dt


def _extract_step_velocity(trajectory: list[dict]) -> float:
    """Extract average forward velocity using step-position gate."""
    enter_state = None
    for state in trajectory:
        if state["pos"][0] >= STEP_START_X:
            enter_state = state
            break
    if enter_state is None:
        return 0.0
    final_state = trajectory[-1]
    dt = final_state["time"] - enter_state["time"]
    if dt < 1e-6:
        return 0.0
    return (final_state["pos"][0] - enter_state["pos"][0]) / dt


# ---------------------------------------------------------------------------
# Workers (run in subprocess)
# ---------------------------------------------------------------------------

def _run_single(task: tuple) -> dict[str, Any]:
    """Run one simulation trial (no video). Called by multiprocessing pool."""
    from simulation_fast_new import run_simulation

    point, mjcf_path, sim_duration, terrain, ctrl_freq, seed, jitter_deg = task

    sim_params = sim_params_from_point(point)
    sim_params["drive_freq"] = ctrl_freq

    trajectory = run_simulation(
        params=sim_params,
        mjcf_path=mjcf_path,
        sim_duration=sim_duration,
        visualize=False,
        init_yaw_jitter_deg=jitter_deg,
        rng_seed=seed,
        wall_timeout=60.0,
    )

    if trajectory is None or len(trajectory) < 10:
        return {"velocity": 0.0, "failed": True, "seed": seed}

    if terrain == "flat":
        vel = _extract_flat_velocity(trajectory)
    else:
        vel = _extract_step_velocity(trajectory)

    return {"velocity": vel, "failed": False, "seed": seed}


def _run_with_video(task: tuple) -> dict[str, Any]:
    """Run one simulation with video recording. Called by multiprocessing pool."""
    from simulation_fast_new import run_simulation

    point, mjcf_path, sim_duration, terrain, ctrl_freq, seed, jitter_deg, video_path = task

    sim_params = sim_params_from_point(point)
    sim_params["drive_freq"] = ctrl_freq

    trajectory = run_simulation(
        params=sim_params,
        mjcf_path=mjcf_path,
        sim_duration=sim_duration,
        visualize=False,
        record_path=video_path,
        init_yaw_jitter_deg=jitter_deg,
        rng_seed=seed,
        wall_timeout=120.0,
    )

    if trajectory is None or len(trajectory) < 10:
        return {"velocity": 0.0, "failed": True, "video_path": video_path}

    if terrain == "flat":
        vel = _extract_flat_velocity(trajectory)
    else:
        vel = _extract_step_velocity(trajectory)

    return {"velocity": vel, "failed": False, "video_path": video_path}


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Characterize param sets against experimental data")
    parser.add_argument("--n-trials", type=int, default=10, help="Number of jitter trials per condition (default: 10)")
    parser.add_argument("--jitter-deg", type=float, default=2.0, help="Yaw jitter range in degrees (default: 2.0)")
    parser.add_argument("--workers", type=int, default=None, help="Number of parallel workers (default: cpu_count)")
    parser.add_argument("--no-video", action="store_true", help="Skip video recording phase")
    args = parser.parse_args()

    n_trials = args.n_trials
    jitter_deg = args.jitter_deg
    n_workers = args.workers or multiprocessing.cpu_count()

    # Build all 27 experimental conditions
    conditions = []
    for ref in FLAT_REFS:
        conditions.append({
            "terrain": "flat",
            "scene": ref["scene"],
            "freq": ref["ctrl_freq"],
            "target_speed": ref["speed"],
            "mjcf_path": MJCF_PATHS[ref["scene"]],
            "sim_duration": FLAT_SIM_DURATION,
        })
    for ref in STEP_REFS:
        conditions.append({
            "terrain": "step",
            "scene": ref["scene"],
            "freq": ref["ctrl_freq"],
            "target_speed": ref["speed"],
            "mjcf_path": STEP_MJCF_PATHS[ref["scene"]],
            "sim_duration": STEP_SIM_DURATION,
        })

    # Verify step XMLs exist
    for scene, path in STEP_MJCF_PATHS.items():
        if not pathlib.Path(path).exists():
            print(f"ERROR: Step XML missing: {path}")
            print("Run optimizer_step.py once to generate step XMLs, or check paths.")
            sys.exit(1)

    # Load 3 parameter sets
    param_sets = {}
    for name, run_dir in PARAM_SETS.items():
        params = load_best_params(run_dir)
        point = params_dict_to_point(params)
        with open(pathlib.Path(run_dir) / "optimization_bests.csv") as f:
            rows = list(csv.DictReader(f))
        best_cost = float(rows[-1]["cost"])
        best_eval = rows[-1]["n_eval"]
        param_sets[name] = {"params": params, "point": point}
        print(f"Loaded {name}: best cost={best_cost:.4f} @ eval {best_eval}")

    # =========================================================================
    # PHASE 1: Run all jitter trials, select best-fit
    # =========================================================================
    print(f"\n{'='*100}")
    print("PHASE 1: Running jitter trials")
    print(f"{'='*100}")

    tasks = []
    task_index = []  # (param_set_name, condition_idx, trial_idx)

    for ps_name, ps_data in param_sets.items():
        point = ps_data["point"]
        for ci, cond in enumerate(conditions):
            for trial in range(n_trials):
                seed = 42000 + hash((ps_name, ci, trial)) % 100000
                tasks.append((
                    point, cond["mjcf_path"], cond["sim_duration"],
                    cond["terrain"], cond["freq"], seed, jitter_deg,
                ))
                task_index.append((ps_name, ci, trial))

    total_sims = len(tasks)
    print(f"Running {total_sims} simulations ({len(param_sets)} param sets x {len(conditions)} conditions x {n_trials} trials)")
    print(f"  Jitter: +/-{jitter_deg} deg, Workers: {n_workers}")
    t0 = time.time()

    with multiprocessing.Pool(n_workers) as pool:
        results_list = pool.map(_run_single, tasks)

    elapsed = time.time() - t0
    print(f"Completed in {elapsed:.1f}s ({total_sims / elapsed:.1f} sims/s)")

    # Collect per-trial results
    # trial_data[ps_name][ci] = [(velocity, seed, failed), ...]
    trial_data: dict[str, dict[int, list]] = {ps: {} for ps in param_sets}
    for (ps_name, ci, trial), result in zip(task_index, results_list):
        if ci not in trial_data[ps_name]:
            trial_data[ps_name][ci] = []
        trial_data[ps_name][ci].append((result["velocity"], result["seed"], result["failed"]))

    # Select best-fit trial per condition (closest velocity to target)
    # best_fit[ps_name][ci] = {"velocity": ..., "seed": ..., "trial_idx": ...}
    best_fit: dict[str, dict[int, dict]] = {ps: {} for ps in param_sets}

    for ps_name in param_sets:
        for ci, cond in enumerate(conditions):
            target = cond["target_speed"]
            trials = trial_data[ps_name][ci]

            best_idx = 0
            best_err = float("inf")
            for i, (vel, seed, failed) in enumerate(trials):
                if failed:
                    continue
                err = abs(vel - target)
                if err < best_err:
                    best_err = err
                    best_idx = i

            vel, seed, failed = trials[best_idx]
            all_vels = [v for v, s, f in trials if not f]

            best_fit[ps_name][ci] = {
                "velocity": vel,
                "seed": seed,
                "trial_idx": best_idx,
                "failed": failed,
                "std_vel": float(np.std(all_vels)) if all_vels else 0.0,
            }

    # =========================================================================
    # Print comparison table
    # =========================================================================
    ps_names = list(param_sets.keys())

    print(f"\n{'='*140}")
    print("CHARACTERIZATION RESULTS: Best-Fit Trial (m/s)")
    print(f"{'='*140}")

    header = f"{'Terrain':<6} {'Morph':<6} {'Hz':<4} {'Expt':<8}"
    for ps in ps_names:
        header += f" | {ps:<12} {'err%':<7}"
    print(header)
    print("-" * 140)

    for terrain_label in ["flat", "step"]:
        for ci, cond in enumerate(conditions):
            if cond["terrain"] != terrain_label:
                continue
            morph = MORPH_MAP.get(cond["scene"], cond["scene"])
            target = cond["target_speed"]

            row = f"{cond['terrain']:<6} {morph:<6} {int(cond['freq']):<4} {target:<8.4f}"

            for ps in ps_names:
                entry = best_fit[ps][ci]
                sim_vel = entry["velocity"]

                if target > 1e-4:
                    err_pct = (sim_vel - target) / target * 100
                    err_str = f"{err_pct:>+6.1f}%"
                else:
                    err_str = f"{'N/A':>7}" if abs(sim_vel) < 0.005 else f"{sim_vel*1000:>5.1f}mm"

                row += f" | {sim_vel:<12.4f} {err_str}"

            print(row)

        if terrain_label == "flat":
            print("-" * 140)

    print("=" * 140)

    # Summary stats
    print("\nSUMMARY (mean absolute % error, best-fit trial):")
    for ps in ps_names:
        flat_errs = []
        step_errs = []
        for ci, cond in enumerate(conditions):
            target = cond["target_speed"]
            if target < 1e-4:
                continue
            sim_vel = best_fit[ps][ci]["velocity"]
            err = abs(sim_vel - target) / target * 100
            if cond["terrain"] == "flat":
                flat_errs.append(err)
            else:
                step_errs.append(err)
        all_errs = flat_errs + step_errs
        print(f"  {ps:<20}: flat={np.mean(flat_errs):>6.1f}%  step={np.mean(step_errs):>6.1f}%  overall={np.mean(all_errs):>6.1f}%")

    # Save CSV
    out_csv = "characterization_results.csv"
    with open(out_csv, "w", newline="") as f:
        writer = csv.writer(f)
        header_row = ["terrain", "scene", "morphology", "freq_hz", "target_speed"]
        for ps in ps_names:
            header_row.extend([f"{ps}_sim_vel", f"{ps}_err_pct", f"{ps}_best_seed"])
        writer.writerow(header_row)

        for ci, cond in enumerate(conditions):
            morph = MORPH_MAP.get(cond["scene"], cond["scene"])
            row = [cond["terrain"], cond["scene"], morph, int(cond["freq"]), cond["target_speed"]]
            for ps in ps_names:
                entry = best_fit[ps][ci]
                target = cond["target_speed"]
                err_pct = ((entry["velocity"] - target) / target * 100) if target > 1e-4 else None
                row.extend([
                    f"{entry['velocity']:.6f}",
                    f"{err_pct:.2f}" if err_pct is not None else "",
                    entry["seed"],
                ])
            writer.writerow(row)
    print(f"\nResults saved to {out_csv}")

    # =========================================================================
    # PHASE 2: Record videos for best-fit trials
    # =========================================================================
    if args.no_video:
        print("\nSkipping video recording (--no-video)")
        return

    print(f"\n{'='*100}")
    print("PHASE 2: Recording best-fit trial videos")
    print(f"{'='*100}")

    video_dir = pathlib.Path("characterization_videos")
    video_tasks = []

    for ps_name, ps_data in param_sets.items():
        ps_dir = video_dir / ps_name
        ps_dir.mkdir(parents=True, exist_ok=True)

        point = ps_data["point"]
        for ci, cond in enumerate(conditions):
            entry = best_fit[ps_name][ci]
            morph = MORPH_MAP.get(cond["scene"], cond["scene"])
            video_path = str(ps_dir / f"{cond['terrain']}_{morph}_f{int(cond['freq'])}.mp4")

            video_tasks.append((
                point, cond["mjcf_path"], cond["sim_duration"],
                cond["terrain"], cond["freq"], entry["seed"], jitter_deg,
                video_path,
            ))

    print(f"Recording {len(video_tasks)} videos to {video_dir}/")
    t0 = time.time()

    # Video recording uses renderer — limit parallelism to avoid GPU contention
    video_workers = min(n_workers, 4)
    with multiprocessing.Pool(video_workers) as pool:
        video_results = pool.map(_run_with_video, video_tasks)

    elapsed = time.time() - t0
    n_ok = sum(1 for r in video_results if not r["failed"])
    print(f"Recorded {n_ok}/{len(video_tasks)} videos in {elapsed:.1f}s")
    print(f"Videos saved to {video_dir}/")


if __name__ == "__main__":
    main()
